# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(data: {clerkId: "user_3FQtuGpamyEJnA1s1iJ9XdUbnCJ", email: "farizfadliansyah@gmail.com", imageUrl: "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMVDI5LThGVmhURTFWV0YzQWN1QjA2aXFXdktvd1V4TnVwcTRsd1QzelBDWjFBRTVWWT1zMTAwMC1jIiwicyI6ImhRTzN1L1NMN3Iza09xeFhnNXNSU0o1T1EyNnNpV0VYdDFiK28zdGRmOWMifQ", username: "fariz fadliansyah"})
}